# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: c


jobs:
  include:
    - name: "Python 3.7 on Xenial Linux"
      os: linux
      language: c
      env: PYTHON_VERSION=3.7

    - name: "Python 3.8 on Xenial Linux"
      os: linux
      language: c
      env: PYTHON_VERSION=3.8

    - name: "Python 3.7 on OSX"
      os: osx
      language: generic
      env: PYTHON_VERSION=3.7

    - name: "Python 3.8 on OSX"
      os: osx
      language: generic
      env: PYTHON_VERSION=3.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
    else
      export OS="Linux";
    fi

  # Wait for mysql service to respond
#  - sleep 5;
#  - mysql -e "CREATE USER 'msnoise'@'localhost' IDENTIFIED BY 'msnoise';";
#  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'msnoise'@'localhost';";
#  - mysql -e "FLUSH PRIVILEGES;";
#  - mysql -e "CREATE DATABASE msnoise;";
  # MySQL database
  # Python and related stuff
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --add channels conda-forge
  - conda config --add channels conda-forge
  - conda update -q --yes conda
  # Installs required packages
  - conda install --yes -q pip python=$PYTHON_VERSION
  - conda install --yes -q numpy scipy matplotlib pandas sqlalchemy pytables xarray
  - conda install --yes -q sphinx jinja2 flask pymysql click
  - conda install --yes -q lxml pyqt
  - conda install --yes -q -c conda-forge obspy
  - conda install --yes -q -c conda-forge flask-admin markdown codecov
  - pip install logbook
  - ls -la

install:
  - python setup.py install
  - cd

script:
  - mkdir empty
  - cd empty
  - msnoise --help
  - msnoise utils bugreport -s -m -e
  - cd ..
  - mkdir MSNoiseTest
  - cd MSNoiseTest
  - coverage run --include='*/msnoise/*/*','*/msnoise/*' -m msnoise.test.tests
  - codecov
